<%
REM -------------------------------------------------------------------------
REM  /ZTITools/All.inc
REM -------------------------------------------------------------------------
REM  Descricao   : Include de Defaults
REM  Cria‡ao     : 11:23h 7/2/1998
REM  Local       : Brasilia/DF
REM  Elaborado   : Ruben Zevallos Jr. <zevallos@zevallos.com.br>
REM  Versao      : 1.0.0
REM  Copyright   : 1998, 1999 by Zevallos(r) Tecnologia em Informacao
REM -------------------------------------------------------------------------
REM  ALTERACOES
REM -------------------------------------------------------------------------
REM  Responsavel : [Nome do executante da alteracao]
REM  Data/Hora   : [Data e hora da alteracao]
REM  Resumo      : [Resumo descritivo da alteracao executada]
REM -------------------------------------------------------------------------
%>
<!--#INCLUDE VIRTUAL="/ZTITools/Initializer.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/AdoVbs.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/Show.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/Error.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/Path.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/Convert.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/File.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/Character.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/Database.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/Table.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/Calendar.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/String.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/Default.inc"--> 
<!--#INCLUDE VIRTUAL="/ZTITools/URL.inc"-->

<%
REM -------------------------------------------------------------------------
REM Fim do All.inc
%>