<?xml version="1.0" encoding="UTF-8"?>
<!-- <% Response.End % >-->
<page id="dbms" name="DBMS" template="single.html" theme="classic" culture="" published="2"><metas><title>dbms samples</title><description></description><keywords></keywords></metas><placeholders><placeholder id="left" pagesize="10" paging="false"><content id="{52c43259-3b33-43eb-9521-3379edef9aa1}" name="All menus" contenttype="navigation_allmenu" startdatetime="200311141416" enddatetime="" published="true" writer="" box="" cachetimeout=""/><content id="{732fbbf1-9746-4457-9937-195185b2537b}" name="Search:" contenttype="search_box" startdatetime="200311172039" enddatetime="" published="true" writer="" box="normal.html" cachetimeout="60"/></placeholder><placeholder id="main" pagesize="10" paging="false"><content id="{d4cbabd4-0330-4282-a6dc-4edc2edeef57}" name="The ADOXSL content type" contenttype="system_html" startdatetime="200311130855" enddatetime="" published="true" writer="john" box="simple.html" cachetimeout="60"><html><![CDATA[The <STRONG>adoxsl</STRONG> content type allow us to display datas stored into any kind of database. This content take 3 parameters:
<LI>the ADO connection string to the database. (ex: SQL server, access, mysql, oracle, cvs, etc. : ado driver needed) 
<LI>The SQL query 
<LI>The path to an XSLT stylesheet that will&nbsp;transform the recordset to HTML.&nbsp;</LI>
<P>
<HR>
<BR><EM>The sample below demonstrate a simple use with an access database.</EM> <BR>Here is the value of the parameters:
<P></P>
<LI>Provider=Microsoft.Jet.OLEDB.4.0;Data Source={{servermappath}}\modules\dbms\samples\tool.mdb;User Id=;Password 
<LI>SELECT * FROM TToolAlbums order BY year ASC 
<LI>{{servermappath}}\modules\dbms\samples\adoxml.xslt </LI>]]></html></content><content id="{a12107bc-6eaf-4615-a703-71cb77bb880d}" name="Ado xsl - sample" contenttype="dbms_adoxsl" startdatetime="200311121449" enddatetime="" published="true" writer="john" box="normal.html" cachetimeout="60"><connectionstring><![CDATA[Provider=Microsoft.Jet.OLEDB.4.0;Data Source={{servermappath}}\modules\dbms\samples\tool.mdb;User Id=;Password=;]]></connectionstring><sqlquery><![CDATA[SELECT * FROM TToolAlbums order BY year ASC]]></sqlquery><xsltemplate><![CDATA[{{servermappath}}\modules\dbms\samples\adoxml.xslt]]></xsltemplate></content></placeholder><placeholder id="pagetab" pagesize="10" paging="false"><content id="{10a010b1-5235-4329-b454-25a8339456f4}" name="Webpage name" contenttype="website_pagename" startdatetime="200311121530" enddatetime="" published="true" writer="" box="" cachetimeout="60"/></placeholder><placeholder id="top" pagesize="10" paging="false"><content id="{29d96a26-aff9-488f-add8-72bb806b0020}" name="Banner" contenttype="system_image" startdatetime="200311121530" enddatetime="" published="true" writer="" box="" cachetimeout="60"><path><![CDATA[media\banner.gif]]></path><width><![CDATA[]]></width><height><![CDATA[]]></height><border><![CDATA[0]]></border><align><![CDATA[center]]></align><valign><![CDATA[ ]]></valign><hspace><![CDATA[0]]></hspace><vspace><![CDATA[0]]></vspace><link><![CDATA[http://www.fullxml.com]]></link><target><![CDATA[_blank]]></target></content></placeholder><placeholder id="top_left" pagesize="10" paging="false"><content id="{7fd7700b-1850-47df-92cd-bf881fdfe366}" name="Website name" contenttype="website_name" startdatetime="200311130853" enddatetime="" published="true" writer="" box="" cachetimeout="60"/><content id="{aeb96f49-eb38-47fe-999b-dfb1f7c806ca}" name="Website slogan" contenttype="website_slogan" startdatetime="200311130853" enddatetime="" published="true" writer="" box="" cachetimeout="60"/></placeholder><placeholder id="bottom" pagesize="10" paging="false"><content id="{369b6224-7950-4592-b24a-97579f0245cd}" name="Website copyright" contenttype="website_copyright" startdatetime="200311130853" enddatetime="" published="true" writer="" box="" cachetimeout="60"/></placeholder><placeholder id="hzone" pagesize="10" paging="false"/></placeholders></page>
