<%@ LANGUAGE="VBSCRIPT" %>
<!--#INCLUDE VIRTUAL="/ZTITools/Show.inc"-->
<!--#INCLUDE VIRTUAL="/ZTITools/File.inc"-->
<!--#INCLUDE VIRTUAL="/ZTITools/Path.inc"-->
<!--#INCLUDE VIRTUAL="/ZTITools/Character.inc"-->
<!--#INCLUDE VIRTUAL="/ZTITools/Convert.inc"-->

<%
On Error Resume Next

ShowHTML "<html>"
ShowHTML "<head>"
ShowHTML "<meta http-equiv=pragma Content=no-cache>"
ShowHTML "<title>Graphical Characters</title>"
ShowHTML "</head>"
REM ShowHTML "<body background=/ztitools/img/assinatura75back.gif bgcolor=white text=black>"
ShowHTML "<body bgcolor=white text=black>"
ShowMessageError """" & ConvAscii2Latin1("R") & """"

ShowHTML "<table width=100% border=0>"

ShowHTML "<tr><td width=1% valing=top><img src=/ztitools/img/assinatura75.gif alt=" & Chr(34) & "Logo - Zevallos - Tecnologia em Informacao" & Chr(34) & ">"
ShowHTML "<td><h1 align=center>Graphical Characters</h1>"
ShowHTML "</table>"
ShowHTML "<hr>"
ShowMessage "Numeros"
ShowMessage "Abacus - "
ShowNumbers "1234567890", "Abacus"
ShowMessage "Default - "
ShowNumbers "1234567890", "Default"
ShowMessage "Odometer - "
ShowNumbers "1234567890", "Odometer"
ShowMessage "Chevy - "
ShowNumbers "1234567890", "Chevy"
ShowMessage "Green - "
ShowNumbers "1234567890", "Green"
ShowHTML "<P>"
ShowMessage "Caracteres"
ShowHTML "<BR>"
ShowMessage "Cilinder"
ShowHTML "<BR>"
ShowGraphString "ABCDEFGHIJKLMNOPQRSTUVWXYZ¡…Õ”⁄›¿»Ã“ŸƒÀœ÷‹¬ Œ‘€√’«", "Cil"
ShowHTML "<BR>"
ShowGraphString "abcdefghijklmnopqrstuvwxyz·ÈÌÛ˙˝‡ËÏÚ˘‰ÎÔˆ¸‚ÍÓÙ˚„ıÁ", "Cil"
ShowHTMLCR "<BR>"
ShowGraphString "1234567890", "Cil"
ShowHTMLCR "<BR>"
ShowGraphString "Ruben e Priscilla", "Cil"
ShowHTMLCR "<BR>"
ShowGraphString " !@#$%^&*()_-+=:;<>,./?{}\|'" & Chr(34), "Cil"

ShowHTML "<P>"
ShowMessage "Windows"
ShowHTML "<BR>"
ShowGraphString "ABCDEFGHIJKLMNOPQRSTUVWXYZ¡…Õ”⁄›¿»Ã“ŸƒÀœ÷‹¬ Œ‘€√’«", "Win"
ShowHTML "<BR>"
ShowGraphString "abcdefghijklmnopqrstuvwxyz·ÈÌÛ˙˝‡ËÏÚ˘‰ÎÔˆ¸‚ÍÓÙ˚„ıÁ", "Win"
ShowHTMLCR "<BR>"
ShowGraphString "1234567890", "Win"
ShowHTMLCR "<BR>"
ShowGraphString "Ruben e Priscilla", "Win"
ShowHTMLCR "<BR>"
ShowGraphString " !@#$%^&*()_-+=:;<>,./?{}\|'" & Chr(34), "Win"

ShowHTML "<P>"
ShowMessage "Botoes com os caracteres"
ShowMessage "Cilinder"
ShowHTMLCR "<BR>"
ShowButtonCil "Ruben e Priscilla"
ShowHTMLCR "<BR>"
ShowMessage "Windows"
ShowHTML "<P>"
ShowButtonWin "Iniciar Sess„o"
ShowHTML "<P>"
ShowButtonWin "Encerrar Sess„o"
ShowHTML "<P>"
ShowButtonWin "?"
ShowHTML "<P>"
ShowButtonWin "Consultar"
ShowHTML "<P>"
ShowButtonWin "Lista Marca"
ShowHTML "<P>"
ShowButtonWin "Fases do Processo"
ShowHTML "<P>"
ShowButtonWin "Detalhes do Processo"
ShowHTML "<P>"
ShowButtonWin "Inviabilizados"
ShowHTML "<P>"
ShowButtonWin "Cadastro do Titular"
ShowHTML "<P>"
ShowButtonWin "Limpar"
ShowHTML "<P>"
ShowButtonWin "Atualizar Cadastro"
ShowHTML "<P>"
ShowButtonWin "Apagar Formul·rio"
ShowHTML "<P>"
ShowButtonCil "Zevallos Tecnologia em InformaÁ„o"
ShowButtonCil "Empresa"
ShowButtonWin "Historia"
ShowButtonWin "Parceiros"
ShowButtonWin "Projetos"
ShowButtonCil "Servidor"
ShowButtonWin "configuraÁ„o"
ShowButtonWin "caracterÌsticas"

ShowHTML "<P>"
ShowButtonWin "Incluir"
ShowHTML "<P>"
ShowButtonWin "Alterar"
ShowHTML "<P>"
ShowButtonWin "Salvar"
ShowHTML "<P>"
ShowButtonWin "Listagem"
ShowHTML "<P>"
 ShowButtonWin "Apagar"
ShowHTML "<P>"
ShowButtonWin "Excluir"
ShowHTML "<P>"
ShowButtonWin "Atualizar"
ShowHTML "<P>"
ShowButtonWin "Copiar"
ShowHTML "<P>"
ShowButtonWin "Salvar e Incluir"
ShowHTML "<P>"
ShowButtonWin "Salvar e Copiar"
ShowHTML "<P>"
ShowButtonWin "Localizar"
ShowHTML "<P>"
ShowButtonWin "OK"
ShowHTML "<P>"
ShowButtonWin "Sim"
ShowHTML "<P>"
ShowButtonWin "N„o"
ShowHTML "<P>"
ShowButtonWin "Cancelar"

ShowButtonWin "|<"
ShowHTML "<P>"
ShowButtonWin "<"
ShowHTML "<P>"
ShowButtonWin ">|"
ShowHTML "<P>"
ShowButtonWin ">"
ShowHTML "<P>"
ShowButtonWin "?"
ShowHTML "<P>"

ShowHTMLCR "</body>"
ShowHTMLCR "</html>"
%>